### ISSUE TITLE
Error for wrong auth key is not really propagated 

### ISSUE THREAD

**Issue by TheFive** [GillesWHC/deepl-client#9]
If you are using a wrong api key (by accident, license stopped...), the error is not really propagated by the library.

Sample:
```
curl -I "https://api.deepl.com/v2/translate"
```
results in
```
HTTP/2 403 
server: nginx
date: Wed, 01 Jul 2020 19:40:31 GMT
content-length: 0
access-control-allow-origin: *
```

What i get with the following node snippet
```javascript
let d= require("deepl-client");

d.translate(
  {auth_key: "wrong", 
   target_lang: "de", 
   text: "Hello"} )
.then( result => {console.dir("then branch"); console.dir(result);})
.catch( err    =>  {console.dir("catch branch"); console.dir(err) });
```

results in

```
FetchError: invalid json response body at https://api.deepl.com/v2/translate?auth_key=wron&target_lang=de&text=Hello reason: Unexpected end of JSON input
    at /Users/TheFive.osm/development/osmbc/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  message: 'invalid json response body at https://api.deepl.com/v2/translate?auth_key=wron&target_lang=de&text=Hello reason: Unexpected end of JSON input',
  type: 'invalid-json'
}
'then branch'
undefined
```
So the error is put to console, and the Library call does not return an error nor a result

**Comment by TheFive** [comment]
403 is the deepl return code for a wrong auth key.

**Comment by GillesWHC** [comment]
Allright, I'll try to add it in as soon as possible!

**Comment by GillesWHC** [comment]
@TheFive error handling has been added, sorry for the trouble!
